const SENTENCE_PREFIXES = Object.freeze([
  { fr: "Aujourd'hui, ", zh: "今天，" },
  { fr: "En général, ", zh: "一般来说，" },
  { fr: "De temps en temps, ", zh: "有时候，" },
  { fr: "En ce moment, ", zh: "目前，" },
  { fr: "Dans ma vie quotidienne, ", zh: "在我的日常生活中，" }
]);

const BASE_SENTENCES = Object.freeze([
  { fr: "Je me lève à sept heures et je bois un verre d'eau.", zh: "我七点起床，喝一杯水。" },
  { fr: "Je prépare un café avant de commencer ma journée.", zh: "我在开始一天前准备一杯咖啡。" },
  { fr: "Je regarde le ciel pour savoir quel temps il fera.", zh: "我看天空判断天气。" },
  { fr: "Je prends mon petit-déjeuner dans la cuisine.", zh: "我在厨房吃早餐。" },
  { fr: "Je vérifie mon agenda avant de partir.", zh: "出发前我查看日程。" },
  { fr: "Je marche jusqu'à la station de métro.", zh: "我步行到地铁站。" },
  { fr: "J'arrive au bureau un peu avant neuf heures.", zh: "我九点前稍早到办公室。" },
  { fr: "Je réponds à mes messages les plus importants.", zh: "我回复最重要的消息。" },
  { fr: "Je fais une courte pause après deux heures de travail.", zh: "工作两小时后我短暂休息。" },
  { fr: "Je rentre à la maison en écoutant de la musique.", zh: "我听音乐回家。" },
  { fr: "J'apprends dix nouveaux mots français chaque jour.", zh: "我每天学习十个新法语单词。" },
  { fr: "Je révise mes leçons avant de passer un examen.", zh: "考试前我复习功课。" },
  { fr: "Je note les erreurs que je veux corriger.", zh: "我记下想改正的错误。" },
  { fr: "Je lis un article en français pour améliorer mon vocabulaire.", zh: "我读法语文章来提高词汇量。" },
  { fr: "Je parle lentement pour prononcer les mots correctement.", zh: "我放慢语速以正确发音。" },
  { fr: "Je pose une question quand je ne comprends pas.", zh: "不懂时我会提问。" },
  { fr: "Je travaille mieux quand la pièce est calme.", zh: "房间安静时我工作效率更高。" },
  { fr: "Je range mon bureau à la fin de la journée.", zh: "一天结束时我整理书桌。" },
  { fr: "Je prépare la liste des tâches pour demain.", zh: "我准备明天的任务清单。" },
  { fr: "Je vérifie mon emploi du temps avant de prendre un rendez-vous.", zh: "预约前我核对日程。" },
  { fr: "J'achète des fruits et des légumes au marché.", zh: "我在市场买水果和蔬菜。" },
  { fr: "Je lis la liste des ingrédients avant de cuisiner.", zh: "做饭前我看配料表。" },
  { fr: "Je préfère cuisiner à la maison pendant le week-end.", zh: "周末我更喜欢在家做饭。" },
  { fr: "Je goûte le plat avant d'ajouter du sel.", zh: "加盐前我先尝菜。" },
  { fr: "Je mets les restes dans une boîte pour demain.", zh: "我把剩菜装盒留到明天。" },
  { fr: "Je choisis des produits locaux quand c'est possible.", zh: "可能时我选择本地产品。" },
  { fr: "Je compare les prix avant d'acheter quelque chose.", zh: "买东西前我会比较价格。" },
  { fr: "Je paie par carte parce que je n'ai pas de monnaie.", zh: "我用卡付款，因为我没有零钱。" },
  { fr: "Je range les courses dans le réfrigérateur.", zh: "我把采购的东西放进冰箱。" },
  { fr: "Je fais attention à ne pas gaspiller de nourriture.", zh: "我注意不浪费食物。" },
  { fr: "Je consulte le plan avant de prendre le bus.", zh: "坐公交前我查看路线图。" },
  { fr: "J'arrive en avance pour ne pas manquer le train.", zh: "我提前到，以免错过火车。" },
  { fr: "Je préfère voyager avec un seul petit sac.", zh: "我喜欢只带一个小包旅行。" },
  { fr: "Je demande mon chemin quand je suis perdu.", zh: "迷路时我会问路。" },
  { fr: "Je photographie les lieux que je veux visiter.", zh: "我拍下想参观的地方。" },
  { fr: "Je m'assois près de la fenêtre pendant le trajet.", zh: "旅途中我坐在窗边。" },
  { fr: "Je garde mon billet dans une poche facile à atteindre.", zh: "我把票放在容易拿到的口袋里。" },
  { fr: "Je bois de l'eau avant de partir en promenade.", zh: "散步前我喝水。" },
  { fr: "Je rentre avant la nuit pour me sentir en sécurité.", zh: "我天黑前回家，以求安全。" },
  { fr: "Je prépare mes affaires la veille d'un voyage.", zh: "出发前一晚我准备行李。" },
  { fr: "J'appelle ma famille quand j'ai un moment libre.", zh: "有空时我给家人打电话。" },
  { fr: "Je remercie les personnes qui m'aident.", zh: "我感谢帮助我的人。" },
  { fr: "J'écoute attentivement avant de donner mon avis.", zh: "发表意见前我认真倾听。" },
  { fr: "Je préfère discuter calmement quand il y a un problème.", zh: "有问题时我更喜欢平静讨论。" },
  { fr: "Je demande des nouvelles à mes amis.", zh: "我问候朋友的近况。" },
  { fr: "Je partage un repas avec les gens que j'aime.", zh: "我和喜欢的人一起吃饭。" },
  { fr: "Je réponds gentiment même quand je suis pressé.", zh: "即使赶时间，我也友善回复。" },
  { fr: "Je garde le contact avec mes anciens collègues.", zh: "我和以前的同事保持联系。" },
  { fr: "Je respecte les opinions différentes des miennes.", zh: "我尊重和我不同的观点。" },
  { fr: "Je présente mes excuses quand je fais une erreur.", zh: "犯错时我会道歉。" },
  { fr: "Je fais du sport pour rester en bonne santé.", zh: "我运动以保持健康。" },
  { fr: "Je bois suffisamment d'eau pendant la journée.", zh: "我白天喝足够的水。" },
  { fr: "Je dors au moins sept heures quand c'est possible.", zh: "可能时我至少睡七个小时。" },
  { fr: "Je marche un peu après le dîner.", zh: "晚饭后我走一走。" },
  { fr: "Je fais des étirements avant de commencer l'exercice.", zh: "运动前我做拉伸。" },
  { fr: "Je m'arrête quand mon corps me demande de ralentir.", zh: "身体要求放慢时我会停下。" },
  { fr: "Je lis quelques pages avant de dormir.", zh: "睡前我读几页书。" },
  { fr: "Je passe du temps sans mon téléphone.", zh: "我会花时间远离手机。" },
  { fr: "Je choisis une activité qui me détend.", zh: "我选择一项让自己放松的活动。" },
  { fr: "Je prépare mes repas avec des aliments variés.", zh: "我用多样的食材准备饭菜。" },
  { fr: "Je commence par la tâche la plus importante.", zh: "我从最重要的任务开始。" },
  { fr: "Je divise un grand projet en petites étapes.", zh: "我把大项目拆成小步骤。" },
  { fr: "Je garde une liste de mes objectifs.", zh: "我保留一份目标清单。" },
  { fr: "Je réfléchis avant de prendre une décision.", zh: "决定前我会思考。" },
  { fr: "Je prévois du temps pour les imprévus.", zh: "我会为意外情况留时间。" },
  { fr: "Je change mon plan quand la situation l'exige.", zh: "情况需要时我会改变计划。" },
  { fr: "Je célèbre les petits progrès.", zh: "我会庆祝小的进步。" },
  { fr: "Je continue même si les résultats prennent du temps.", zh: "即使结果需要时间，我也会继续。" },
  { fr: "J'accepte de ne pas tout savoir.", zh: "我接受自己不可能什么都知道。" },
  { fr: "Je choisis d'apprendre quelque chose de nouveau chaque semaine.", zh: "我选择每周学习一点新东西。" },
  { fr: "Je profite du soleil quand il y en a.", zh: "有阳光时我会享受它。" },
  { fr: "J'ouvre la fenêtre pour respirer l'air frais.", zh: "我开窗呼吸新鲜空气。" },
  { fr: "Je termine la journée en pensant à ce qui s'est bien passé.", zh: "我回想顺利的事情来结束一天。" }
]);

const lowercaseFirst = (value) => value.charAt(0).toLowerCase() + value.slice(1);

const DAILY_SENTENCES = Object.freeze(
  SENTENCE_PREFIXES.flatMap((prefix) =>
    BASE_SENTENCES.map((sentence) => ({
      fr: prefix.fr + lowercaseFirst(sentence.fr),
      zh: prefix.zh + sentence.zh
    }))
  )
);